# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'nStarMainGUI.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLCDNumber, QLabel, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTabWidget,
    QWidget)

from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from PySide6.QtWidgets import QMainWindow, QVBoxLayout, QWidget


class FitsDisplayWindow(QMainWindow):
  def __init__(self, image_data, vmin=None, vmax=None):
    super().__init__()
    self.setWindowTitle("FITS Display")
    self.resize(700, 700)

    container = QWidget(self)
    layout = QVBoxLayout(container)

    figure = Figure()
    self.canvas = FigureCanvasQTAgg(figure)
    layout.addWidget(self.canvas)

    self.axes = figure.add_subplot(111)
    self.image_artist = self.axes.imshow(
      image_data, cmap="gray", origin="lower", vmin=vmin, vmax=vmax
    )
    #draw circles
    #c = Circle((1000, 1000), radius=50, edgecolor='red', fill=False)
    #self.axes.add_patch(c)

    figure.tight_layout()

    self.setCentralWidget(container)

    

  def set_image_data(self, image_data, vmin=None, vmax=None):
    self.image_artist.set_data(image_data)
    height, width = image_data.shape
    self.image_artist.set_extent(
      (-0.5, width - 0.5, -0.5, height - 0.5)
    )
    self.axes.set_xlim(-0.5, width - 0.5)
    self.axes.set_ylim(-0.5, height - 0.5)
    if vmin is None or vmax is None:
      self.image_artist.autoscale()
    else:
      self.image_artist.set_clim(vmin, vmax)
    self.canvas.draw_idle()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(241, 158)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(241, 158))
        MainWindow.setMaximumSize(QSize(241, 158))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        self.actionImport_FITS = QAction(MainWindow)
        self.actionImport_FITS.setObjectName(u"actionImport_FITS")
        self.actionExport_display = QAction(MainWindow)
        self.actionExport_display.setObjectName(u"actionExport_display")
        self.actionExport_raw_data_txt = QAction(MainWindow)
        self.actionExport_raw_data_txt.setObjectName(u"actionExport_raw_data_txt")
        self.actionIncrease_stretch = QAction(MainWindow)
        self.actionIncrease_stretch.setObjectName(u"actionIncrease_stretch")
        self.actionDecrease_stretch = QAction(MainWindow)
        self.actionDecrease_stretch.setObjectName(u"actionDecrease_stretch")
        self.actionExport_stretched_data_fits = QAction(MainWindow)
        self.actionExport_stretched_data_fits.setObjectName(u"actionExport_stretched_data_fits")
        self.actionRemove_stretch = QAction(MainWindow)
        self.actionRemove_stretch.setObjectName(u"actionRemove_stretch")
        self.actionRemove = QAction(MainWindow)
        self.actionRemove.setObjectName(u"actionRemove")
        self.actionApply = QAction(MainWindow)
        self.actionApply.setObjectName(u"actionApply")
        self.actionDecrease = QAction(MainWindow)
        self.actionDecrease.setObjectName(u"actionDecrease")
        self.actionIncrease = QAction(MainWindow)
        self.actionIncrease.setObjectName(u"actionIncrease")
        self.actionDefault = QAction(MainWindow)
        self.actionDefault.setObjectName(u"actionDefault")
        self.actionView_parameters = QAction(MainWindow)
        self.actionView_parameters.setObjectName(u"actionView_parameters")
        self.actionDisplay_FITS = QAction(MainWindow)
        self.actionDisplay_FITS.setObjectName(u"actionDisplay_FITS")
        self.actionStar_map_2 = QAction(MainWindow)
        self.actionStar_map_2.setObjectName(u"actionStar_map_2")
        self.actionFWHM_map = QAction(MainWindow)
        self.actionFWHM_map.setObjectName(u"actionFWHM_map")
        self.actionEccentricity_map = QAction(MainWindow)
        self.actionEccentricity_map.setObjectName(u"actionEccentricity_map")
        self.actionMajor_axis_angle_map = QAction(MainWindow)
        self.actionMajor_axis_angle_map.setObjectName(u"actionMajor_axis_angle_map")
        self.actionStar_analysis = QAction(MainWindow)
        self.actionStar_analysis.setObjectName(u"actionStar_analysis")
        self.actionFWHM = QAction(MainWindow)
        self.actionFWHM.setObjectName(u"actionFWHM")
        self.actionEccentricity = QAction(MainWindow)
        self.actionEccentricity.setObjectName(u"actionEccentricity")
        self.actionMajor_axis_angle = QAction(MainWindow)
        self.actionMajor_axis_angle.setObjectName(u"actionMajor_axis_angle")
        self.actionFlux = QAction(MainWindow)
        self.actionFlux.setObjectName(u"actionFlux")
        self.actionBackground = QAction(MainWindow)
        self.actionBackground.setObjectName(u"actionBackground")
        self.actionBackground_2 = QAction(MainWindow)
        self.actionBackground_2.setObjectName(u"actionBackground_2")
        self.actionMaximum_pixel_value = QAction(MainWindow)
        self.actionMaximum_pixel_value.setObjectName(u"actionMaximum_pixel_value")
        self.actionMinimum_pixel_value = QAction(MainWindow)
        self.actionMinimum_pixel_value.setObjectName(u"actionMinimum_pixel_value")
        self.actionImage_data_2 = QAction(MainWindow)
        self.actionImage_data_2.setObjectName(u"actionImage_data_2")
        self.actionAnnotate = QAction(MainWindow)
        self.actionAnnotate.setObjectName(u"actionAnnotate")
        self.actionHighlight_stars = QAction(MainWindow)
        self.actionHighlight_stars.setObjectName(u"actionHighlight_stars")
        self.actionHighlight_stars.setCheckable(True)
        self.actionShow_annotations = QAction(MainWindow)
        self.actionShow_annotations.setObjectName(u"actionShow_annotations")
        self.actionShow_annotations.setCheckable(True)
        self.actionAnalyze = QAction(MainWindow)
        self.actionAnalyze.setObjectName(u"actionAnalyze")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(140, 40, 93, 28))
        self.strNum = QLCDNumber(self.centralwidget)
        self.strNum.setObjectName(u"strNum")
        self.strNum.setGeometry(QRect(70, 40, 64, 23))
        self.sensBar = QSlider(self.centralwidget)
        self.sensBar.setObjectName(u"sensBar")
        self.sensBar.setGeometry(QRect(140, 10, 91, 22))
        self.sensBar.setMaximum(100)
        self.sensBar.setSingleStep(1)
        self.sensBar.setSliderPosition(30)
        self.sensBar.setOrientation(Qt.Orientation.Horizontal)
        self.sensBar.setInvertedAppearance(False)
        self.sensBar.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.sensBar.setTickInterval(10)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 61, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 61, 16))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(10, 80, 221, 23))
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)
        self.sensNum = QLCDNumber(self.centralwidget)
        self.sensNum.setObjectName(u"sensNum")
        self.sensNum.setGeometry(QRect(70, 10, 64, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 241, 26))
        self.menuData = QMenu(self.menubar)
        self.menuData.setObjectName(u"menuData")
        self.menuStetch = QMenu(self.menuData)
        self.menuStetch.setObjectName(u"menuStetch")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuVisual = QMenu(self.menuView)
        self.menuVisual.setObjectName(u"menuVisual")
        self.menuRaw = QMenu(self.menuView)
        self.menuRaw.setObjectName(u"menuRaw")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuData.addAction(self.actionAnalyze)
        self.menuData.addSeparator()
        self.menuData.addAction(self.menuStetch.menuAction())
        self.menuData.addAction(self.actionAnnotate)
        self.menuStetch.addAction(self.actionRemove)
        self.menuStetch.addAction(self.actionApply)
        self.menuStetch.addSeparator()
        self.menuStetch.addAction(self.actionDecrease)
        self.menuStetch.addAction(self.actionIncrease)
        self.menuStetch.addSeparator()
        self.menuStetch.addAction(self.actionDefault)
        self.menuStetch.addSeparator()
        self.menuStetch.addAction(self.actionView_parameters)
        self.menuView.addAction(self.actionDisplay_FITS)
        self.menuView.addAction(self.actionHighlight_stars)
        self.menuView.addAction(self.actionShow_annotations)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuVisual.menuAction())
        self.menuView.addAction(self.menuRaw.menuAction())
        self.menuView.addAction(self.actionImage_data_2)
        self.menuVisual.addAction(self.actionStar_map_2)
        self.menuVisual.addAction(self.actionFWHM_map)
        self.menuVisual.addAction(self.actionEccentricity_map)
        self.menuVisual.addAction(self.actionMajor_axis_angle_map)
        self.menuRaw.addAction(self.actionStar_analysis)
        self.menuRaw.addSeparator()
        self.menuRaw.addAction(self.actionFWHM)
        self.menuRaw.addAction(self.actionFlux)
        self.menuRaw.addAction(self.actionEccentricity)
        self.menuRaw.addAction(self.actionMajor_axis_angle)
        self.menuFile.addAction(self.actionImport_FITS)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_display)
        self.menuFile.addAction(self.actionExport_raw_data_txt)
        self.menuFile.addAction(self.actionExport_stretched_data_fits)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"nStar", None))
        self.actionImport_FITS.setText(QCoreApplication.translate("MainWindow", u"Import FITS", None))
        self.actionExport_display.setText(QCoreApplication.translate("MainWindow", u"Export display (.png)", None))
        self.actionExport_raw_data_txt.setText(QCoreApplication.translate("MainWindow", u"Export raw data (.txt)", None))
        self.actionIncrease_stretch.setText(QCoreApplication.translate("MainWindow", u"Increase stretch", None))
        self.actionDecrease_stretch.setText(QCoreApplication.translate("MainWindow", u"Decrease stretch", None))
        self.actionExport_stretched_data_fits.setText(QCoreApplication.translate("MainWindow", u"Export stretched data (.fits)", None))
        self.actionRemove_stretch.setText(QCoreApplication.translate("MainWindow", u"Remove stretch", None))
        self.actionRemove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.actionApply.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.actionDecrease.setText(QCoreApplication.translate("MainWindow", u"Decrease gamma", None))
        self.actionIncrease.setText(QCoreApplication.translate("MainWindow", u"Increase gamma", None))
        self.actionDefault.setText(QCoreApplication.translate("MainWindow", u"Default gamma", None))
        self.actionView_parameters.setText(QCoreApplication.translate("MainWindow", u"View parameters", None))
        self.actionDisplay_FITS.setText(QCoreApplication.translate("MainWindow", u"Display FITS", None))
        self.actionStar_map_2.setText(QCoreApplication.translate("MainWindow", u"Star map", None))
        self.actionFWHM_map.setText(QCoreApplication.translate("MainWindow", u"FWHM map", None))
        self.actionEccentricity_map.setText(QCoreApplication.translate("MainWindow", u"Eccentricity map", None))
        self.actionMajor_axis_angle_map.setText(QCoreApplication.translate("MainWindow", u"Major axis angle map", None))
        self.actionStar_analysis.setText(QCoreApplication.translate("MainWindow", u"All data", None))
        self.actionFWHM.setText(QCoreApplication.translate("MainWindow", u"FWHM", None))
        self.actionEccentricity.setText(QCoreApplication.translate("MainWindow", u"Eccentricity", None))
        self.actionMajor_axis_angle.setText(QCoreApplication.translate("MainWindow", u"Major axis angle", None))
        self.actionFlux.setText(QCoreApplication.translate("MainWindow", u"Flux", None))
        self.actionBackground.setText(QCoreApplication.translate("MainWindow", u"All data", None))
        self.actionBackground_2.setText(QCoreApplication.translate("MainWindow", u"Background", None))
        self.actionMaximum_pixel_value.setText(QCoreApplication.translate("MainWindow", u"Pixel value distribution", None))
        self.actionMinimum_pixel_value.setText(QCoreApplication.translate("MainWindow", u"Minimum pixel value", None))
        self.actionImage_data_2.setText(QCoreApplication.translate("MainWindow", u"Image data", None))
        self.actionAnnotate.setText(QCoreApplication.translate("MainWindow", u"Annotate", None))
        self.actionHighlight_stars.setText(QCoreApplication.translate("MainWindow", u"Highlight stars", None))
        self.actionShow_annotations.setText(QCoreApplication.translate("MainWindow", u"Show annotations", None))
        self.actionAnalyze.setText(QCoreApplication.translate("MainWindow", u"Analyze", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Detect Stars", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sensitivity", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Stars", None))
        self.menuData.setTitle(QCoreApplication.translate("MainWindow", u"Data", None))
        self.menuStetch.setTitle(QCoreApplication.translate("MainWindow", u"Stretch", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuVisual.setTitle(QCoreApplication.translate("MainWindow", u"Visual", None))
        self.menuRaw.setTitle(QCoreApplication.translate("MainWindow", u"Star data", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi
